// src/app.ts
import express10 from "express";
import cors from "cors";

// src/modules/auth/auth.router.ts
import express from "express";

// src/modules/auth/auth.service.ts
import bcrypt from "bcryptjs";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/client.ts
import "process";
import * as path from "path";
import { fileURLToPath } from "url";
import "@prisma/client/runtime/client";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.5.0",
  "engineVersion": "280c870be64f457428992c43c1f6d557fab6e29e",
  "activeProvider": "postgresql",
  "inlineSchema": '// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Get a free hosted Postgres database in seconds: `npx create-db`\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel User {\n  id       String  @id @default(cuid())\n  name     String\n  email    String  @unique\n  password String\n  role     Role    @default(MEMBER)\n  isActive Boolean @default(true)\n\n  ideas     Idea[]\n  comments  Comment[]\n  votes     Vote[]\n  purchases Purchase[]\n\n  createdAt DateTime @default(now())\n}\n\nenum Role {\n  MEMBER\n  ADMIN\n}\n\nmodel Category {\n  id   String @id @default(cuid())\n  name String @unique\n\n  ideas Idea[]\n}\n\nmodel Idea {\n  id          String  @id @default(cuid())\n  title       String\n  problem     String\n  solution    String\n  description String\n  image       String?\n  isFeatured  Boolean @default(false)\n\n  isPaid Boolean @default(false)\n  price  Float?\n\n  status IdeaStatus @default(UNDER_REVIEW)\n\n  authorId String\n  author   User   @relation(fields: [authorId], references: [id], onDelete: Cascade)\n\n  categoryId String\n  category   Category @relation(fields: [categoryId], references: [id], onDelete: Cascade)\n\n  comments  Comment[]\n  votes     Vote[]\n  purchases Purchase[]\n\n  feedback Feedback?\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@index([title])\n  @@index([categoryId])\n}\n\nenum IdeaStatus {\n  UNDER_REVIEW\n  APPROVED\n  REJECTED\n  DRAFT\n}\n\nenum VoteType {\n  UP\n  DOWN\n}\n\nmodel Vote {\n  id String @id @default(cuid())\n\n  userId String\n  ideaId String\n\n  type VoteType\n\n  user User @relation(fields: [userId], references: [id], onDelete: Cascade)\n  idea Idea @relation(fields: [ideaId], references: [id], onDelete: Cascade)\n\n  @@unique([userId, ideaId]) // prevents multiple votes\n}\n\nmodel Comment {\n  id      String @id @default(cuid())\n  content String\n\n  userId String\n  ideaId String\n\n  parentId String? // for nested comments\n\n  user User @relation(fields: [userId], references: [id])\n  idea Idea @relation(fields: [ideaId], references: [id])\n\n  parent  Comment?  @relation("CommentReplies", fields: [parentId], references: [id], onDelete: Cascade)\n  replies Comment[] @relation("CommentReplies")\n\n  createdAt DateTime @default(now())\n}\n\nmodel Feedback {\n  id String @id @default(cuid())\n\n  ideaId  String @unique\n  message String\n\n  idea Idea @relation(fields: [ideaId], references: [id], onDelete: Cascade)\n\n  createdAt DateTime @default(now())\n}\n\nmodel Purchase {\n  id String @id @default(cuid())\n\n  userId String\n  ideaId String\n\n  user User @relation(fields: [userId], references: [id], onDelete: Cascade)\n  idea Idea @relation(fields: [ideaId], references: [id], onDelete: Cascade)\n\n  createdAt DateTime @default(now())\n\n  @@unique([userId, ideaId]) // user buys once\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"Role"},{"name":"isActive","kind":"scalar","type":"Boolean"},{"name":"ideas","kind":"object","type":"Idea","relationName":"IdeaToUser"},{"name":"comments","kind":"object","type":"Comment","relationName":"CommentToUser"},{"name":"votes","kind":"object","type":"Vote","relationName":"UserToVote"},{"name":"purchases","kind":"object","type":"Purchase","relationName":"PurchaseToUser"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"ideas","kind":"object","type":"Idea","relationName":"CategoryToIdea"}],"dbName":null},"Idea":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"title","kind":"scalar","type":"String"},{"name":"problem","kind":"scalar","type":"String"},{"name":"solution","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"image","kind":"scalar","type":"String"},{"name":"isFeatured","kind":"scalar","type":"Boolean"},{"name":"isPaid","kind":"scalar","type":"Boolean"},{"name":"price","kind":"scalar","type":"Float"},{"name":"status","kind":"enum","type":"IdeaStatus"},{"name":"authorId","kind":"scalar","type":"String"},{"name":"author","kind":"object","type":"User","relationName":"IdeaToUser"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToIdea"},{"name":"comments","kind":"object","type":"Comment","relationName":"CommentToIdea"},{"name":"votes","kind":"object","type":"Vote","relationName":"IdeaToVote"},{"name":"purchases","kind":"object","type":"Purchase","relationName":"IdeaToPurchase"},{"name":"feedback","kind":"object","type":"Feedback","relationName":"FeedbackToIdea"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Vote":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"ideaId","kind":"scalar","type":"String"},{"name":"type","kind":"enum","type":"VoteType"},{"name":"user","kind":"object","type":"User","relationName":"UserToVote"},{"name":"idea","kind":"object","type":"Idea","relationName":"IdeaToVote"}],"dbName":null},"Comment":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"content","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"ideaId","kind":"scalar","type":"String"},{"name":"parentId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"CommentToUser"},{"name":"idea","kind":"object","type":"Idea","relationName":"CommentToIdea"},{"name":"parent","kind":"object","type":"Comment","relationName":"CommentReplies"},{"name":"replies","kind":"object","type":"Comment","relationName":"CommentReplies"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Feedback":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"ideaId","kind":"scalar","type":"String"},{"name":"message","kind":"scalar","type":"String"},{"name":"idea","kind":"object","type":"Idea","relationName":"FeedbackToIdea"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Purchase":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"ideaId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"PurchaseToUser"},{"name":"idea","kind":"object","type":"Idea","relationName":"IdeaToPurchase"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","author","ideas","_count","category","user","idea","parent","replies","comments","votes","purchases","feedback","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","Idea.findUnique","Idea.findUniqueOrThrow","Idea.findFirst","Idea.findFirstOrThrow","Idea.findMany","Idea.createOne","Idea.createMany","Idea.createManyAndReturn","Idea.updateOne","Idea.updateMany","Idea.updateManyAndReturn","Idea.upsertOne","Idea.deleteOne","Idea.deleteMany","_avg","_sum","Idea.groupBy","Idea.aggregate","Vote.findUnique","Vote.findUniqueOrThrow","Vote.findFirst","Vote.findFirstOrThrow","Vote.findMany","Vote.createOne","Vote.createMany","Vote.createManyAndReturn","Vote.updateOne","Vote.updateMany","Vote.updateManyAndReturn","Vote.upsertOne","Vote.deleteOne","Vote.deleteMany","Vote.groupBy","Vote.aggregate","Comment.findUnique","Comment.findUniqueOrThrow","Comment.findFirst","Comment.findFirstOrThrow","Comment.findMany","Comment.createOne","Comment.createMany","Comment.createManyAndReturn","Comment.updateOne","Comment.updateMany","Comment.updateManyAndReturn","Comment.upsertOne","Comment.deleteOne","Comment.deleteMany","Comment.groupBy","Comment.aggregate","Feedback.findUnique","Feedback.findUniqueOrThrow","Feedback.findFirst","Feedback.findFirstOrThrow","Feedback.findMany","Feedback.createOne","Feedback.createMany","Feedback.createManyAndReturn","Feedback.updateOne","Feedback.updateMany","Feedback.updateManyAndReturn","Feedback.upsertOne","Feedback.deleteOne","Feedback.deleteMany","Feedback.groupBy","Feedback.aggregate","Purchase.findUnique","Purchase.findUniqueOrThrow","Purchase.findFirst","Purchase.findFirstOrThrow","Purchase.findMany","Purchase.createOne","Purchase.createMany","Purchase.createManyAndReturn","Purchase.updateOne","Purchase.updateMany","Purchase.updateManyAndReturn","Purchase.upsertOne","Purchase.deleteOne","Purchase.deleteMany","Purchase.groupBy","Purchase.aggregate","AND","OR","NOT","id","userId","ideaId","createdAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","message","content","parentId","VoteType","type","title","problem","solution","description","image","isFeatured","isPaid","price","IdeaStatus","status","authorId","categoryId","updatedAt","name","every","some","none","email","password","Role","role","isActive","userId_ideaId","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "7gM_cA4EAADoAQAgCwAA8AEAIAwAAPEBACANAADyAQAghwEAAO0BADCIAQAAJQAQiQEAAO0BADCKAQEAAAABjQFAANEBACGrAQEA0AEAIa8BAQAAAAGwAQEA0AEAIbIBAADuAbIBIrMBIADvAQAhAQAAAAEAIBcDAAD1AQAgBgAA_wEAIAsAAPABACAMAADxAQAgDQAA8gEAIA4AAIACACCHAQAA_AEAMIgBAAADABCJAQAA_AEAMIoBAQDQAQAhjQFAANEBACGeAQEA0AEAIZ8BAQDQAQAhoAEBANABACGhAQEA0AEAIaIBAQD6AQAhowEgAO8BACGkASAA7wEAIaUBCAD9AQAhpwEAAP4BpwEiqAEBANABACGpAQEA0AEAIaoBQADRAQAhCAMAALADACAGAACyAwAgCwAArQMAIAwAAK4DACANAACvAwAgDgAAswMAIKIBAACQAgAgpQEAAJACACAXAwAA9QEAIAYAAP8BACALAADwAQAgDAAA8QEAIA0AAPIBACAOAACAAgAghwEAAPwBADCIAQAAAwAQiQEAAPwBADCKAQEAAAABjQFAANEBACGeAQEA0AEAIZ8BAQDQAQAhoAEBANABACGhAQEA0AEAIaIBAQD6AQAhowEgAO8BACGkASAA7wEAIaUBCAD9AQAhpwEAAP4BpwEiqAEBANABACGpAQEA0AEAIaoBQADRAQAhAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACABAAAAAwAgDQcAAPUBACAIAADSAQAgCQAA-wEAIAoAAPABACCHAQAA-QEAMIgBAAAJABCJAQAA-QEAMIoBAQDQAQAhiwEBANABACGMAQEA0AEAIY0BQADRAQAhmgEBANABACGbAQEA-gEAIQUHAACwAwAgCAAAjwIAIAkAALEDACAKAACtAwAgmwEAAJACACANBwAA9QEAIAgAANIBACAJAAD7AQAgCgAA8AEAIIcBAAD5AQAwiAEAAAkAEIkBAAD5AQAwigEBAAAAAYsBAQDQAQAhjAEBANABACGNAUAA0QEAIZoBAQDQAQAhmwEBAPoBACEDAAAACQAgAQAACgAwAgAACwAgAQAAAAkAIAMAAAAJACABAAAKADACAAALACABAAAACQAgCQcAAPUBACAIAADSAQAghwEAAPcBADCIAQAAEAAQiQEAAPcBADCKAQEA0AEAIYsBAQDQAQAhjAEBANABACGdAQAA-AGdASICBwAAsAMAIAgAAI8CACAKBwAA9QEAIAgAANIBACCHAQAA9wEAMIgBAAAQABCJAQAA9wEAMIoBAQAAAAGLAQEA0AEAIYwBAQDQAQAhnQEAAPgBnQEitAEAAPYBACADAAAAEAAgAQAAEQAwAgAAEgAgCQcAAPUBACAIAADSAQAghwEAAPQBADCIAQAAFAAQiQEAAPQBADCKAQEA0AEAIYsBAQDQAQAhjAEBANABACGNAUAA0QEAIQIHAACwAwAgCAAAjwIAIAoHAAD1AQAgCAAA0gEAIIcBAAD0AQAwiAEAABQAEIkBAAD0AQAwigEBAAAAAYsBAQDQAQAhjAEBANABACGNAUAA0QEAIbQBAADzAQAgAwAAABQAIAEAABUAMAIAABYAIAgIAADSAQAghwEAAM8BADCIAQAAGAAQiQEAAM8BADCKAQEA0AEAIYwBAQDQAQAhjQFAANEBACGZAQEA0AEAIQEAAAAYACABAAAACQAgAQAAABAAIAEAAAAUACADAAAACQAgAQAACgAwAgAACwAgAwAAABAAIAEAABEAMAIAABIAIAMAAAAUACABAAAVADACAAAWACABAAAAAwAgAQAAAAkAIAEAAAAQACABAAAAFAAgAQAAAAEAIA4EAADoAQAgCwAA8AEAIAwAAPEBACANAADyAQAghwEAAO0BADCIAQAAJQAQiQEAAO0BADCKAQEA0AEAIY0BQADRAQAhqwEBANABACGvAQEA0AEAIbABAQDQAQAhsgEAAO4BsgEiswEgAO8BACEEBAAA_AIAIAsAAK0DACAMAACuAwAgDQAArwMAIAMAAAAlACABAAAmADACAAABACADAAAAJQAgAQAAJgAwAgAAAQAgAwAAACUAIAEAACYAMAIAAAEAIAsEAACpAwAgCwAAqgMAIAwAAKsDACANAACsAwAgigEBAAAAAY0BQAAAAAGrAQEAAAABrwEBAAAAAbABAQAAAAGyAQAAALIBArMBIAAAAAEBFAAAKgAgB4oBAQAAAAGNAUAAAAABqwEBAAAAAa8BAQAAAAGwAQEAAAABsgEAAACyAQKzASAAAAABARQAACwAMAEUAAAsADALBAAAgQMAIAsAAIIDACAMAACDAwAgDQAAhAMAIIoBAQCEAgAhjQFAAIUCACGrAQEAhAIAIa8BAQCEAgAhsAEBAIQCACGyAQAAgAOyASKzASAAtgIAIQIAAAABACAUAAAvACAHigEBAIQCACGNAUAAhQIAIasBAQCEAgAhrwEBAIQCACGwAQEAhAIAIbIBAACAA7IBIrMBIAC2AgAhAgAAACUAIBQAADEAIAIAAAAlACAUAAAxACADAAAAAQAgGwAAKgAgHAAALwAgAQAAAAEAIAEAAAAlACADBQAA_QIAICEAAP8CACAiAAD-AgAgCocBAADpAQAwiAEAADgAEIkBAADpAQAwigEBAMcBACGNAUAAyAEAIasBAQDHAQAhrwEBAMcBACGwAQEAxwEAIbIBAADqAbIBIrMBIADdAQAhAwAAACUAIAEAADcAMCAAADgAIAMAAAAlACABAAAmADACAAABACAGBAAA6AEAIIcBAADnAQAwiAEAAD4AEIkBAADnAQAwigEBAAAAAasBAQAAAAEBAAAAOwAgAQAAADsAIAYEAADoAQAghwEAAOcBADCIAQAAPgAQiQEAAOcBADCKAQEA0AEAIasBAQDQAQAhAQQAAPwCACADAAAAPgAgAQAAPwAwAgAAOwAgAwAAAD4AIAEAAD8AMAIAADsAIAMAAAA-ACABAAA_ADACAAA7ACADBAAA-wIAIIoBAQAAAAGrAQEAAAABARQAAEMAIAKKAQEAAAABqwEBAAAAAQEUAABFADABFAAARQAwAwQAAO4CACCKAQEAhAIAIasBAQCEAgAhAgAAADsAIBQAAEgAIAKKAQEAhAIAIasBAQCEAgAhAgAAAD4AIBQAAEoAIAIAAAA-ACAUAABKACADAAAAOwAgGwAAQwAgHAAASAAgAQAAADsAIAEAAAA-ACADBQAA6wIAICEAAO0CACAiAADsAgAgBYcBAADmAQAwiAEAAFEAEIkBAADmAQAwigEBAMcBACGrAQEAxwEAIQMAAAA-ACABAABQADAgAABRACADAAAAPgAgAQAAPwAwAgAAOwAgAQAAAAUAIAEAAAAFACADAAAAAwAgAQAABAAwAgAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACAUAwAA5QIAIAYAAOYCACALAADnAgAgDAAA6AIAIA0AAOkCACAOAADqAgAgigEBAAAAAY0BQAAAAAGeAQEAAAABnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBIAAAAAGkASAAAAABpQEIAAAAAacBAAAApwECqAEBAAAAAakBAQAAAAGqAUAAAAABARQAAFkAIA6KAQEAAAABjQFAAAAAAZ4BAQAAAAGfAQEAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEgAAAAAaQBIAAAAAGlAQgAAAABpwEAAACnAQKoAQEAAAABqQEBAAAAAaoBQAAAAAEBFAAAWwAwARQAAFsAMBQDAAC5AgAgBgAAugIAIAsAALsCACAMAAC8AgAgDQAAvQIAIA4AAL4CACCKAQEAhAIAIY0BQACFAgAhngEBAIQCACGfAQEAhAIAIaABAQCEAgAhoQEBAIQCACGiAQEAlAIAIaMBIAC2AgAhpAEgALYCACGlAQgAtwIAIacBAAC4AqcBIqgBAQCEAgAhqQEBAIQCACGqAUAAhQIAIQIAAAAFACAUAABeACAOigEBAIQCACGNAUAAhQIAIZ4BAQCEAgAhnwEBAIQCACGgAQEAhAIAIaEBAQCEAgAhogEBAJQCACGjASAAtgIAIaQBIAC2AgAhpQEIALcCACGnAQAAuAKnASKoAQEAhAIAIakBAQCEAgAhqgFAAIUCACECAAAAAwAgFAAAYAAgAgAAAAMAIBQAAGAAIAMAAAAFACAbAABZACAcAABeACABAAAABQAgAQAAAAMAIAcFAACxAgAgIQAAtAIAICIAALMCACBDAACyAgAgRAAAtQIAIKIBAACQAgAgpQEAAJACACARhwEAANwBADCIAQAAZwAQiQEAANwBADCKAQEAxwEAIY0BQADIAQAhngEBAMcBACGfAQEAxwEAIaABAQDHAQAhoQEBAMcBACGiAQEA1AEAIaMBIADdAQAhpAEgAN0BACGlAQgA3gEAIacBAADfAacBIqgBAQDHAQAhqQEBAMcBACGqAUAAyAEAIQMAAAADACABAABmADAgAABnACADAAAAAwAgAQAABAAwAgAABQAgAQAAABIAIAEAAAASACADAAAAEAAgAQAAEQAwAgAAEgAgAwAAABAAIAEAABEAMAIAABIAIAMAAAAQACABAAARADACAAASACAGBwAArwIAIAgAALACACCKAQEAAAABiwEBAAAAAYwBAQAAAAGdAQAAAJ0BAgEUAABvACAEigEBAAAAAYsBAQAAAAGMAQEAAAABnQEAAACdAQIBFAAAcQAwARQAAHEAMAYHAACtAgAgCAAArgIAIIoBAQCEAgAhiwEBAIQCACGMAQEAhAIAIZ0BAACsAp0BIgIAAAASACAUAAB0ACAEigEBAIQCACGLAQEAhAIAIYwBAQCEAgAhnQEAAKwCnQEiAgAAABAAIBQAAHYAIAIAAAAQACAUAAB2ACADAAAAEgAgGwAAbwAgHAAAdAAgAQAAABIAIAEAAAAQACADBQAAqQIAICEAAKsCACAiAACqAgAgB4cBAADYAQAwiAEAAH0AEIkBAADYAQAwigEBAMcBACGLAQEAxwEAIYwBAQDHAQAhnQEAANkBnQEiAwAAABAAIAEAAHwAMCAAAH0AIAMAAAAQACABAAARADACAAASACABAAAACwAgAQAAAAsAIAMAAAAJACABAAAKADACAAALACADAAAACQAgAQAACgAwAgAACwAgAwAAAAkAIAEAAAoAMAIAAAsAIAoHAAClAgAgCAAApgIAIAkAAKgCACAKAACnAgAgigEBAAAAAYsBAQAAAAGMAQEAAAABjQFAAAAAAZoBAQAAAAGbAQEAAAABARQAAIUBACAGigEBAAAAAYsBAQAAAAGMAQEAAAABjQFAAAAAAZoBAQAAAAGbAQEAAAABARQAAIcBADABFAAAhwEAMAEAAAAJACAKBwAAlQIAIAgAAJYCACAJAACXAgAgCgAAmAIAIIoBAQCEAgAhiwEBAIQCACGMAQEAhAIAIY0BQACFAgAhmgEBAIQCACGbAQEAlAIAIQIAAAALACAUAACLAQAgBooBAQCEAgAhiwEBAIQCACGMAQEAhAIAIY0BQACFAgAhmgEBAIQCACGbAQEAlAIAIQIAAAAJACAUAACNAQAgAgAAAAkAIBQAAI0BACABAAAACQAgAwAAAAsAIBsAAIUBACAcAACLAQAgAQAAAAsAIAEAAAAJACAEBQAAkQIAICEAAJMCACAiAACSAgAgmwEAAJACACAJhwEAANMBADCIAQAAlQEAEIkBAADTAQAwigEBAMcBACGLAQEAxwEAIYwBAQDHAQAhjQFAAMgBACGaAQEAxwEAIZsBAQDUAQAhAwAAAAkAIAEAAJQBADAgAACVAQAgAwAAAAkAIAEAAAoAMAIAAAsAIAgIAADSAQAghwEAAM8BADCIAQAAGAAQiQEAAM8BADCKAQEAAAABjAEBAAAAAY0BQADRAQAhmQEBANABACEBAAAAmAEAIAEAAACYAQAgAQgAAI8CACADAAAAGAAgAQAAmwEAMAIAAJgBACADAAAAGAAgAQAAmwEAMAIAAJgBACADAAAAGAAgAQAAmwEAMAIAAJgBACAFCAAAjgIAIIoBAQAAAAGMAQEAAAABjQFAAAAAAZkBAQAAAAEBFAAAnwEAIASKAQEAAAABjAEBAAAAAY0BQAAAAAGZAQEAAAABARQAAKEBADABFAAAoQEAMAUIAACNAgAgigEBAIQCACGMAQEAhAIAIY0BQACFAgAhmQEBAIQCACECAAAAmAEAIBQAAKQBACAEigEBAIQCACGMAQEAhAIAIY0BQACFAgAhmQEBAIQCACECAAAAGAAgFAAApgEAIAIAAAAYACAUAACmAQAgAwAAAJgBACAbAACfAQAgHAAApAEAIAEAAACYAQAgAQAAABgAIAMFAACKAgAgIQAAjAIAICIAAIsCACAHhwEAAM4BADCIAQAArQEAEIkBAADOAQAwigEBAMcBACGMAQEAxwEAIY0BQADIAQAhmQEBAMcBACEDAAAAGAAgAQAArAEAMCAAAK0BACADAAAAGAAgAQAAmwEAMAIAAJgBACABAAAAFgAgAQAAABYAIAMAAAAUACABAAAVADACAAAWACADAAAAFAAgAQAAFQAwAgAAFgAgAwAAABQAIAEAABUAMAIAABYAIAYHAACIAgAgCAAAiQIAIIoBAQAAAAGLAQEAAAABjAEBAAAAAY0BQAAAAAEBFAAAtQEAIASKAQEAAAABiwEBAAAAAYwBAQAAAAGNAUAAAAABARQAALcBADABFAAAtwEAMAYHAACGAgAgCAAAhwIAIIoBAQCEAgAhiwEBAIQCACGMAQEAhAIAIY0BQACFAgAhAgAAABYAIBQAALoBACAEigEBAIQCACGLAQEAhAIAIYwBAQCEAgAhjQFAAIUCACECAAAAFAAgFAAAvAEAIAIAAAAUACAUAAC8AQAgAwAAABYAIBsAALUBACAcAAC6AQAgAQAAABYAIAEAAAAUACADBQAAgQIAICEAAIMCACAiAACCAgAgB4cBAADGAQAwiAEAAMMBABCJAQAAxgEAMIoBAQDHAQAhiwEBAMcBACGMAQEAxwEAIY0BQADIAQAhAwAAABQAIAEAAMIBADAgAADDAQAgAwAAABQAIAEAABUAMAIAABYAIAeHAQAAxgEAMIgBAADDAQAQiQEAAMYBADCKAQEAxwEAIYsBAQDHAQAhjAEBAMcBACGNAUAAyAEAIQ4FAADKAQAgIQAAzQEAICIAAM0BACCOAQEAAAABjwEBAAAABJABAQAAAASRAQEAAAABkgEBAAAAAZMBAQAAAAGUAQEAAAABlQEBAMwBACGWAQEAAAABlwEBAAAAAZgBAQAAAAELBQAAygEAICEAAMsBACAiAADLAQAgjgFAAAAAAY8BQAAAAASQAUAAAAAEkQFAAAAAAZIBQAAAAAGTAUAAAAABlAFAAAAAAZUBQADJAQAhCwUAAMoBACAhAADLAQAgIgAAywEAII4BQAAAAAGPAUAAAAAEkAFAAAAABJEBQAAAAAGSAUAAAAABkwFAAAAAAZQBQAAAAAGVAUAAyQEAIQiOAQIAAAABjwECAAAABJABAgAAAASRAQIAAAABkgECAAAAAZMBAgAAAAGUAQIAAAABlQECAMoBACEIjgFAAAAAAY8BQAAAAASQAUAAAAAEkQFAAAAAAZIBQAAAAAGTAUAAAAABlAFAAAAAAZUBQADLAQAhDgUAAMoBACAhAADNAQAgIgAAzQEAII4BAQAAAAGPAQEAAAAEkAEBAAAABJEBAQAAAAGSAQEAAAABkwEBAAAAAZQBAQAAAAGVAQEAzAEAIZYBAQAAAAGXAQEAAAABmAEBAAAAAQuOAQEAAAABjwEBAAAABJABAQAAAASRAQEAAAABkgEBAAAAAZMBAQAAAAGUAQEAAAABlQEBAM0BACGWAQEAAAABlwEBAAAAAZgBAQAAAAEHhwEAAM4BADCIAQAArQEAEIkBAADOAQAwigEBAMcBACGMAQEAxwEAIY0BQADIAQAhmQEBAMcBACEICAAA0gEAIIcBAADPAQAwiAEAABgAEIkBAADPAQAwigEBANABACGMAQEA0AEAIY0BQADRAQAhmQEBANABACELjgEBAAAAAY8BAQAAAASQAQEAAAAEkQEBAAAAAZIBAQAAAAGTAQEAAAABlAEBAAAAAZUBAQDNAQAhlgEBAAAAAZcBAQAAAAGYAQEAAAABCI4BQAAAAAGPAUAAAAAEkAFAAAAABJEBQAAAAAGSAUAAAAABkwFAAAAAAZQBQAAAAAGVAUAAywEAIRkDAAD1AQAgBgAA_wEAIAsAAPABACAMAADxAQAgDQAA8gEAIA4AAIACACCHAQAA_AEAMIgBAAADABCJAQAA_AEAMIoBAQDQAQAhjQFAANEBACGeAQEA0AEAIZ8BAQDQAQAhoAEBANABACGhAQEA0AEAIaIBAQD6AQAhowEgAO8BACGkASAA7wEAIaUBCAD9AQAhpwEAAP4BpwEiqAEBANABACGpAQEA0AEAIaoBQADRAQAhtQEAAAMAILYBAAADACAJhwEAANMBADCIAQAAlQEAEIkBAADTAQAwigEBAMcBACGLAQEAxwEAIYwBAQDHAQAhjQFAAMgBACGaAQEAxwEAIZsBAQDUAQAhDgUAANYBACAhAADXAQAgIgAA1wEAII4BAQAAAAGPAQEAAAAFkAEBAAAABZEBAQAAAAGSAQEAAAABkwEBAAAAAZQBAQAAAAGVAQEA1QEAIZYBAQAAAAGXAQEAAAABmAEBAAAAAQ4FAADWAQAgIQAA1wEAICIAANcBACCOAQEAAAABjwEBAAAABZABAQAAAAWRAQEAAAABkgEBAAAAAZMBAQAAAAGUAQEAAAABlQEBANUBACGWAQEAAAABlwEBAAAAAZgBAQAAAAEIjgECAAAAAY8BAgAAAAWQAQIAAAAFkQECAAAAAZIBAgAAAAGTAQIAAAABlAECAAAAAZUBAgDWAQAhC44BAQAAAAGPAQEAAAAFkAEBAAAABZEBAQAAAAGSAQEAAAABkwEBAAAAAZQBAQAAAAGVAQEA1wEAIZYBAQAAAAGXAQEAAAABmAEBAAAAAQeHAQAA2AEAMIgBAAB9ABCJAQAA2AEAMIoBAQDHAQAhiwEBAMcBACGMAQEAxwEAIZ0BAADZAZ0BIgcFAADKAQAgIQAA2wEAICIAANsBACCOAQAAAJ0BAo8BAAAAnQEIkAEAAACdAQiVAQAA2gGdASIHBQAAygEAICEAANsBACAiAADbAQAgjgEAAACdAQKPAQAAAJ0BCJABAAAAnQEIlQEAANoBnQEiBI4BAAAAnQECjwEAAACdAQiQAQAAAJ0BCJUBAADbAZ0BIhGHAQAA3AEAMIgBAABnABCJAQAA3AEAMIoBAQDHAQAhjQFAAMgBACGeAQEAxwEAIZ8BAQDHAQAhoAEBAMcBACGhAQEAxwEAIaIBAQDUAQAhowEgAN0BACGkASAA3QEAIaUBCADeAQAhpwEAAN8BpwEiqAEBAMcBACGpAQEAxwEAIaoBQADIAQAhBQUAAMoBACAhAADlAQAgIgAA5QEAII4BIAAAAAGVASAA5AEAIQ0FAADWAQAgIQAA4wEAICIAAOMBACBDAADjAQAgRAAA4wEAII4BCAAAAAGPAQgAAAAFkAEIAAAABZEBCAAAAAGSAQgAAAABkwEIAAAAAZQBCAAAAAGVAQgA4gEAIQcFAADKAQAgIQAA4QEAICIAAOEBACCOAQAAAKcBAo8BAAAApwEIkAEAAACnAQiVAQAA4AGnASIHBQAAygEAICEAAOEBACAiAADhAQAgjgEAAACnAQKPAQAAAKcBCJABAAAApwEIlQEAAOABpwEiBI4BAAAApwECjwEAAACnAQiQAQAAAKcBCJUBAADhAacBIg0FAADWAQAgIQAA4wEAICIAAOMBACBDAADjAQAgRAAA4wEAII4BCAAAAAGPAQgAAAAFkAEIAAAABZEBCAAAAAGSAQgAAAABkwEIAAAAAZQBCAAAAAGVAQgA4gEAIQiOAQgAAAABjwEIAAAABZABCAAAAAWRAQgAAAABkgEIAAAAAZMBCAAAAAGUAQgAAAABlQEIAOMBACEFBQAAygEAICEAAOUBACAiAADlAQAgjgEgAAAAAZUBIADkAQAhAo4BIAAAAAGVASAA5QEAIQWHAQAA5gEAMIgBAABRABCJAQAA5gEAMIoBAQDHAQAhqwEBAMcBACEGBAAA6AEAIIcBAADnAQAwiAEAAD4AEIkBAADnAQAwigEBANABACGrAQEA0AEAIQOsAQAAAwAgrQEAAAMAIK4BAAADACAKhwEAAOkBADCIAQAAOAAQiQEAAOkBADCKAQEAxwEAIY0BQADIAQAhqwEBAMcBACGvAQEAxwEAIbABAQDHAQAhsgEAAOoBsgEiswEgAN0BACEHBQAAygEAICEAAOwBACAiAADsAQAgjgEAAACyAQKPAQAAALIBCJABAAAAsgEIlQEAAOsBsgEiBwUAAMoBACAhAADsAQAgIgAA7AEAII4BAAAAsgECjwEAAACyAQiQAQAAALIBCJUBAADrAbIBIgSOAQAAALIBAo8BAAAAsgEIkAEAAACyAQiVAQAA7AGyASIOBAAA6AEAIAsAAPABACAMAADxAQAgDQAA8gEAIIcBAADtAQAwiAEAACUAEIkBAADtAQAwigEBANABACGNAUAA0QEAIasBAQDQAQAhrwEBANABACGwAQEA0AEAIbIBAADuAbIBIrMBIADvAQAhBI4BAAAAsgECjwEAAACyAQiQAQAAALIBCJUBAADsAbIBIgKOASAAAAABlQEgAOUBACEDrAEAAAkAIK0BAAAJACCuAQAACQAgA6wBAAAQACCtAQAAEAAgrgEAABAAIAOsAQAAFAAgrQEAABQAIK4BAAAUACACiwEBAAAAAYwBAQAAAAEJBwAA9QEAIAgAANIBACCHAQAA9AEAMIgBAAAUABCJAQAA9AEAMIoBAQDQAQAhiwEBANABACGMAQEA0AEAIY0BQADRAQAhEAQAAOgBACALAADwAQAgDAAA8QEAIA0AAPIBACCHAQAA7QEAMIgBAAAlABCJAQAA7QEAMIoBAQDQAQAhjQFAANEBACGrAQEA0AEAIa8BAQDQAQAhsAEBANABACGyAQAA7gGyASKzASAA7wEAIbUBAAAlACC2AQAAJQAgAosBAQAAAAGMAQEAAAABCQcAAPUBACAIAADSAQAghwEAAPcBADCIAQAAEAAQiQEAAPcBADCKAQEA0AEAIYsBAQDQAQAhjAEBANABACGdAQAA-AGdASIEjgEAAACdAQKPAQAAAJ0BCJABAAAAnQEIlQEAANsBnQEiDQcAAPUBACAIAADSAQAgCQAA-wEAIAoAAPABACCHAQAA-QEAMIgBAAAJABCJAQAA-QEAMIoBAQDQAQAhiwEBANABACGMAQEA0AEAIY0BQADRAQAhmgEBANABACGbAQEA-gEAIQuOAQEAAAABjwEBAAAABZABAQAAAAWRAQEAAAABkgEBAAAAAZMBAQAAAAGUAQEAAAABlQEBANcBACGWAQEAAAABlwEBAAAAAZgBAQAAAAEPBwAA9QEAIAgAANIBACAJAAD7AQAgCgAA8AEAIIcBAAD5AQAwiAEAAAkAEIkBAAD5AQAwigEBANABACGLAQEA0AEAIYwBAQDQAQAhjQFAANEBACGaAQEA0AEAIZsBAQD6AQAhtQEAAAkAILYBAAAJACAXAwAA9QEAIAYAAP8BACALAADwAQAgDAAA8QEAIA0AAPIBACAOAACAAgAghwEAAPwBADCIAQAAAwAQiQEAAPwBADCKAQEA0AEAIY0BQADRAQAhngEBANABACGfAQEA0AEAIaABAQDQAQAhoQEBANABACGiAQEA-gEAIaMBIADvAQAhpAEgAO8BACGlAQgA_QEAIacBAAD-AacBIqgBAQDQAQAhqQEBANABACGqAUAA0QEAIQiOAQgAAAABjwEIAAAABZABCAAAAAWRAQgAAAABkgEIAAAAAZMBCAAAAAGUAQgAAAABlQEIAOMBACEEjgEAAACnAQKPAQAAAKcBCJABAAAApwEIlQEAAOEBpwEiCAQAAOgBACCHAQAA5wEAMIgBAAA-ABCJAQAA5wEAMIoBAQDQAQAhqwEBANABACG1AQAAPgAgtgEAAD4AIAoIAADSAQAghwEAAM8BADCIAQAAGAAQiQEAAM8BADCKAQEA0AEAIYwBAQDQAQAhjQFAANEBACGZAQEA0AEAIbUBAAAYACC2AQAAGAAgAAAAAboBAQAAAAEBugFAAAAAAQUbAADnAwAgHAAA7QMAILcBAADoAwAguAEAAOwDACC9AQAAAQAgBRsAAOUDACAcAADqAwAgtwEAAOYDACC4AQAA6QMAIL0BAAAFACADGwAA5wMAILcBAADoAwAgvQEAAAEAIAMbAADlAwAgtwEAAOYDACC9AQAABQAgAAAABRsAAOADACAcAADjAwAgtwEAAOEDACC4AQAA4gMAIL0BAAAFACADGwAA4AMAILcBAADhAwAgvQEAAAUAIAgDAACwAwAgBgAAsgMAIAsAAK0DACAMAACuAwAgDQAArwMAIA4AALMDACCiAQAAkAIAIKUBAACQAgAgAAAAAAG6AQEAAAABBRsAANQDACAcAADeAwAgtwEAANUDACC4AQAA3QMAIL0BAAABACAFGwAA0gMAIBwAANsDACC3AQAA0wMAILgBAADaAwAgvQEAAAUAIAcbAADQAwAgHAAA2AMAILcBAADRAwAguAEAANcDACC7AQAACQAgvAEAAAkAIL0BAAALACALGwAAmQIAMBwAAJ4CADC3AQAAmgIAMLgBAACbAgAwuQEAAJwCACC6AQAAnQIAMLsBAACdAgAwvAEAAJ0CADC9AQAAnQIAML4BAACfAgAwvwEAAKACADAIBwAApQIAIAgAAKYCACAKAACnAgAgigEBAAAAAYsBAQAAAAGMAQEAAAABjQFAAAAAAZoBAQAAAAECAAAACwAgGwAApAIAIAMAAAALACAbAACkAgAgHAAAowIAIAEUAADWAwAwDQcAAPUBACAIAADSAQAgCQAA-wEAIAoAAPABACCHAQAA-QEAMIgBAAAJABCJAQAA-QEAMIoBAQAAAAGLAQEA0AEAIYwBAQDQAQAhjQFAANEBACGaAQEA0AEAIZsBAQD6AQAhAgAAAAsAIBQAAKMCACACAAAAoQIAIBQAAKICACAJhwEAAKACADCIAQAAoQIAEIkBAACgAgAwigEBANABACGLAQEA0AEAIYwBAQDQAQAhjQFAANEBACGaAQEA0AEAIZsBAQD6AQAhCYcBAACgAgAwiAEAAKECABCJAQAAoAIAMIoBAQDQAQAhiwEBANABACGMAQEA0AEAIY0BQADRAQAhmgEBANABACGbAQEA-gEAIQWKAQEAhAIAIYsBAQCEAgAhjAEBAIQCACGNAUAAhQIAIZoBAQCEAgAhCAcAAJUCACAIAACWAgAgCgAAmAIAIIoBAQCEAgAhiwEBAIQCACGMAQEAhAIAIY0BQACFAgAhmgEBAIQCACEIBwAApQIAIAgAAKYCACAKAACnAgAgigEBAAAAAYsBAQAAAAGMAQEAAAABjQFAAAAAAZoBAQAAAAEDGwAA1AMAILcBAADVAwAgvQEAAAEAIAMbAADSAwAgtwEAANMDACC9AQAABQAgBBsAAJkCADC3AQAAmgIAMLkBAACcAgAgvQEAAJ0CADADGwAA0AMAILcBAADRAwAgvQEAAAsAIAAAAAG6AQAAAJ0BAgUbAADIAwAgHAAAzgMAILcBAADJAwAguAEAAM0DACC9AQAAAQAgBRsAAMYDACAcAADLAwAgtwEAAMcDACC4AQAAygMAIL0BAAAFACADGwAAyAMAILcBAADJAwAgvQEAAAEAIAMbAADGAwAgtwEAAMcDACC9AQAABQAgAAAAAAABugEgAAAAAQW6AQgAAAABwAEIAAAAAcEBCAAAAAHCAQgAAAABwwEIAAAAAQG6AQAAAKcBAgUbAAC7AwAgHAAAxAMAILcBAAC8AwAguAEAAMMDACC9AQAAAQAgBRsAALkDACAcAADBAwAgtwEAALoDACC4AQAAwAMAIL0BAAA7ACALGwAA3AIAMBwAAOACADC3AQAA3QIAMLgBAADeAgAwuQEAAN8CACC6AQAAnQIAMLsBAACdAgAwvAEAAJ0CADC9AQAAnQIAML4BAADhAgAwvwEAAKACADALGwAA0AIAMBwAANUCADC3AQAA0QIAMLgBAADSAgAwuQEAANMCACC6AQAA1AIAMLsBAADUAgAwvAEAANQCADC9AQAA1AIAML4BAADWAgAwvwEAANcCADALGwAAxAIAMBwAAMkCADC3AQAAxQIAMLgBAADGAgAwuQEAAMcCACC6AQAAyAIAMLsBAADIAgAwvAEAAMgCADC9AQAAyAIAML4BAADKAgAwvwEAAMsCADAHGwAAvwIAIBwAAMICACC3AQAAwAIAILgBAADBAgAguwEAABgAILwBAAAYACC9AQAAmAEAIAOKAQEAAAABjQFAAAAAAZkBAQAAAAECAAAAmAEAIBsAAL8CACADAAAAGAAgGwAAvwIAIBwAAMMCACAFAAAAGAAgFAAAwwIAIIoBAQCEAgAhjQFAAIUCACGZAQEAhAIAIQOKAQEAhAIAIY0BQACFAgAhmQEBAIQCACEEBwAAiAIAIIoBAQAAAAGLAQEAAAABjQFAAAAAAQIAAAAWACAbAADPAgAgAwAAABYAIBsAAM8CACAcAADOAgAgARQAAL8DADAKBwAA9QEAIAgAANIBACCHAQAA9AEAMIgBAAAUABCJAQAA9AEAMIoBAQAAAAGLAQEA0AEAIYwBAQDQAQAhjQFAANEBACG0AQAA8wEAIAIAAAAWACAUAADOAgAgAgAAAMwCACAUAADNAgAgB4cBAADLAgAwiAEAAMwCABCJAQAAywIAMIoBAQDQAQAhiwEBANABACGMAQEA0AEAIY0BQADRAQAhB4cBAADLAgAwiAEAAMwCABCJAQAAywIAMIoBAQDQAQAhiwEBANABACGMAQEA0AEAIY0BQADRAQAhA4oBAQCEAgAhiwEBAIQCACGNAUAAhQIAIQQHAACGAgAgigEBAIQCACGLAQEAhAIAIY0BQACFAgAhBAcAAIgCACCKAQEAAAABiwEBAAAAAY0BQAAAAAEEBwAArwIAIIoBAQAAAAGLAQEAAAABnQEAAACdAQICAAAAEgAgGwAA2wIAIAMAAAASACAbAADbAgAgHAAA2gIAIAEUAAC-AwAwCgcAAPUBACAIAADSAQAghwEAAPcBADCIAQAAEAAQiQEAAPcBADCKAQEAAAABiwEBANABACGMAQEA0AEAIZ0BAAD4AZ0BIrQBAAD2AQAgAgAAABIAIBQAANoCACACAAAA2AIAIBQAANkCACAHhwEAANcCADCIAQAA2AIAEIkBAADXAgAwigEBANABACGLAQEA0AEAIYwBAQDQAQAhnQEAAPgBnQEiB4cBAADXAgAwiAEAANgCABCJAQAA1wIAMIoBAQDQAQAhiwEBANABACGMAQEA0AEAIZ0BAAD4AZ0BIgOKAQEAhAIAIYsBAQCEAgAhnQEAAKwCnQEiBAcAAK0CACCKAQEAhAIAIYsBAQCEAgAhnQEAAKwCnQEiBAcAAK8CACCKAQEAAAABiwEBAAAAAZ0BAAAAnQECCAcAAKUCACAJAACoAgAgCgAApwIAIIoBAQAAAAGLAQEAAAABjQFAAAAAAZoBAQAAAAGbAQEAAAABAgAAAAsAIBsAAOQCACADAAAACwAgGwAA5AIAIBwAAOMCACABFAAAvQMAMAIAAAALACAUAADjAgAgAgAAAKECACAUAADiAgAgBYoBAQCEAgAhiwEBAIQCACGNAUAAhQIAIZoBAQCEAgAhmwEBAJQCACEIBwAAlQIAIAkAAJcCACAKAACYAgAgigEBAIQCACGLAQEAhAIAIY0BQACFAgAhmgEBAIQCACGbAQEAlAIAIQgHAAClAgAgCQAAqAIAIAoAAKcCACCKAQEAAAABiwEBAAAAAY0BQAAAAAGaAQEAAAABmwEBAAAAAQMbAAC7AwAgtwEAALwDACC9AQAAAQAgAxsAALkDACC3AQAAugMAIL0BAAA7ACAEGwAA3AIAMLcBAADdAgAwuQEAAN8CACC9AQAAnQIAMAQbAADQAgAwtwEAANECADC5AQAA0wIAIL0BAADUAgAwBBsAAMQCADC3AQAAxQIAMLkBAADHAgAgvQEAAMgCADADGwAAvwIAILcBAADAAgAgvQEAAJgBACAAAAALGwAA7wIAMBwAAPQCADC3AQAA8AIAMLgBAADxAgAwuQEAAPICACC6AQAA8wIAMLsBAADzAgAwvAEAAPMCADC9AQAA8wIAML4BAAD1AgAwvwEAAPYCADASAwAA5QIAIAsAAOcCACAMAADoAgAgDQAA6QIAIA4AAOoCACCKAQEAAAABjQFAAAAAAZ4BAQAAAAGfAQEAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEgAAAAAaQBIAAAAAGlAQgAAAABpwEAAACnAQKoAQEAAAABqgFAAAAAAQIAAAAFACAbAAD6AgAgAwAAAAUAIBsAAPoCACAcAAD5AgAgARQAALgDADAXAwAA9QEAIAYAAP8BACALAADwAQAgDAAA8QEAIA0AAPIBACAOAACAAgAghwEAAPwBADCIAQAAAwAQiQEAAPwBADCKAQEAAAABjQFAANEBACGeAQEA0AEAIZ8BAQDQAQAhoAEBANABACGhAQEA0AEAIaIBAQD6AQAhowEgAO8BACGkASAA7wEAIaUBCAD9AQAhpwEAAP4BpwEiqAEBANABACGpAQEA0AEAIaoBQADRAQAhAgAAAAUAIBQAAPkCACACAAAA9wIAIBQAAPgCACARhwEAAPYCADCIAQAA9wIAEIkBAAD2AgAwigEBANABACGNAUAA0QEAIZ4BAQDQAQAhnwEBANABACGgAQEA0AEAIaEBAQDQAQAhogEBAPoBACGjASAA7wEAIaQBIADvAQAhpQEIAP0BACGnAQAA_gGnASKoAQEA0AEAIakBAQDQAQAhqgFAANEBACERhwEAAPYCADCIAQAA9wIAEIkBAAD2AgAwigEBANABACGNAUAA0QEAIZ4BAQDQAQAhnwEBANABACGgAQEA0AEAIaEBAQDQAQAhogEBAPoBACGjASAA7wEAIaQBIADvAQAhpQEIAP0BACGnAQAA_gGnASKoAQEA0AEAIakBAQDQAQAhqgFAANEBACENigEBAIQCACGNAUAAhQIAIZ4BAQCEAgAhnwEBAIQCACGgAQEAhAIAIaEBAQCEAgAhogEBAJQCACGjASAAtgIAIaQBIAC2AgAhpQEIALcCACGnAQAAuAKnASKoAQEAhAIAIaoBQACFAgAhEgMAALkCACALAAC7AgAgDAAAvAIAIA0AAL0CACAOAAC-AgAgigEBAIQCACGNAUAAhQIAIZ4BAQCEAgAhnwEBAIQCACGgAQEAhAIAIaEBAQCEAgAhogEBAJQCACGjASAAtgIAIaQBIAC2AgAhpQEIALcCACGnAQAAuAKnASKoAQEAhAIAIaoBQACFAgAhEgMAAOUCACALAADnAgAgDAAA6AIAIA0AAOkCACAOAADqAgAgigEBAAAAAY0BQAAAAAGeAQEAAAABnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBIAAAAAGkASAAAAABpQEIAAAAAacBAAAApwECqAEBAAAAAaoBQAAAAAEEGwAA7wIAMLcBAADwAgAwuQEAAPICACC9AQAA8wIAMAAAAAABugEAAACyAQILGwAAoAMAMBwAAKQDADC3AQAAoQMAMLgBAACiAwAwuQEAAKMDACC6AQAA8wIAMLsBAADzAgAwvAEAAPMCADC9AQAA8wIAML4BAAClAwAwvwEAAPYCADALGwAAlwMAMBwAAJsDADC3AQAAmAMAMLgBAACZAwAwuQEAAJoDACC6AQAAnQIAMLsBAACdAgAwvAEAAJ0CADC9AQAAnQIAML4BAACcAwAwvwEAAKACADALGwAAjgMAMBwAAJIDADC3AQAAjwMAMLgBAACQAwAwuQEAAJEDACC6AQAA1AIAMLsBAADUAgAwvAEAANQCADC9AQAA1AIAML4BAACTAwAwvwEAANcCADALGwAAhQMAMBwAAIkDADC3AQAAhgMAMLgBAACHAwAwuQEAAIgDACC6AQAAyAIAMLsBAADIAgAwvAEAAMgCADC9AQAAyAIAML4BAACKAwAwvwEAAMsCADAECAAAiQIAIIoBAQAAAAGMAQEAAAABjQFAAAAAAQIAAAAWACAbAACNAwAgAwAAABYAIBsAAI0DACAcAACMAwAgARQAALcDADACAAAAFgAgFAAAjAMAIAIAAADMAgAgFAAAiwMAIAOKAQEAhAIAIYwBAQCEAgAhjQFAAIUCACEECAAAhwIAIIoBAQCEAgAhjAEBAIQCACGNAUAAhQIAIQQIAACJAgAgigEBAAAAAYwBAQAAAAGNAUAAAAABBAgAALACACCKAQEAAAABjAEBAAAAAZ0BAAAAnQECAgAAABIAIBsAAJYDACADAAAAEgAgGwAAlgMAIBwAAJUDACABFAAAtgMAMAIAAAASACAUAACVAwAgAgAAANgCACAUAACUAwAgA4oBAQCEAgAhjAEBAIQCACGdAQAArAKdASIECAAArgIAIIoBAQCEAgAhjAEBAIQCACGdAQAArAKdASIECAAAsAIAIIoBAQAAAAGMAQEAAAABnQEAAACdAQIICAAApgIAIAkAAKgCACAKAACnAgAgigEBAAAAAYwBAQAAAAGNAUAAAAABmgEBAAAAAZsBAQAAAAECAAAACwAgGwAAnwMAIAMAAAALACAbAACfAwAgHAAAngMAIAEUAAC1AwAwAgAAAAsAIBQAAJ4DACACAAAAoQIAIBQAAJ0DACAFigEBAIQCACGMAQEAhAIAIY0BQACFAgAhmgEBAIQCACGbAQEAlAIAIQgIAACWAgAgCQAAlwIAIAoAAJgCACCKAQEAhAIAIYwBAQCEAgAhjQFAAIUCACGaAQEAhAIAIZsBAQCUAgAhCAgAAKYCACAJAACoAgAgCgAApwIAIIoBAQAAAAGMAQEAAAABjQFAAAAAAZoBAQAAAAGbAQEAAAABEgYAAOYCACALAADnAgAgDAAA6AIAIA0AAOkCACAOAADqAgAgigEBAAAAAY0BQAAAAAGeAQEAAAABnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBIAAAAAGkASAAAAABpQEIAAAAAacBAAAApwECqQEBAAAAAaoBQAAAAAECAAAABQAgGwAAqAMAIAMAAAAFACAbAACoAwAgHAAApwMAIAEUAAC0AwAwAgAAAAUAIBQAAKcDACACAAAA9wIAIBQAAKYDACANigEBAIQCACGNAUAAhQIAIZ4BAQCEAgAhnwEBAIQCACGgAQEAhAIAIaEBAQCEAgAhogEBAJQCACGjASAAtgIAIaQBIAC2AgAhpQEIALcCACGnAQAAuAKnASKpAQEAhAIAIaoBQACFAgAhEgYAALoCACALAAC7AgAgDAAAvAIAIA0AAL0CACAOAAC-AgAgigEBAIQCACGNAUAAhQIAIZ4BAQCEAgAhnwEBAIQCACGgAQEAhAIAIaEBAQCEAgAhogEBAJQCACGjASAAtgIAIaQBIAC2AgAhpQEIALcCACGnAQAAuAKnASKpAQEAhAIAIaoBQACFAgAhEgYAAOYCACALAADnAgAgDAAA6AIAIA0AAOkCACAOAADqAgAgigEBAAAAAY0BQAAAAAGeAQEAAAABnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBIAAAAAGkASAAAAABpQEIAAAAAacBAAAApwECqQEBAAAAAaoBQAAAAAEEGwAAoAMAMLcBAAChAwAwuQEAAKMDACC9AQAA8wIAMAQbAACXAwAwtwEAAJgDADC5AQAAmgMAIL0BAACdAgAwBBsAAI4DADC3AQAAjwMAMLkBAACRAwAgvQEAANQCADAEGwAAhQMAMLcBAACGAwAwuQEAAIgDACC9AQAAyAIAMAAAAAQEAAD8AgAgCwAArQMAIAwAAK4DACANAACvAwAgBQcAALADACAIAACPAgAgCQAAsQMAIAoAAK0DACCbAQAAkAIAIAEEAAD8AgAgAQgAAI8CACANigEBAAAAAY0BQAAAAAGeAQEAAAABnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBIAAAAAGkASAAAAABpQEIAAAAAacBAAAApwECqQEBAAAAAaoBQAAAAAEFigEBAAAAAYwBAQAAAAGNAUAAAAABmgEBAAAAAZsBAQAAAAEDigEBAAAAAYwBAQAAAAGdAQAAAJ0BAgOKAQEAAAABjAEBAAAAAY0BQAAAAAENigEBAAAAAY0BQAAAAAGeAQEAAAABnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBIAAAAAGkASAAAAABpQEIAAAAAacBAAAApwECqAEBAAAAAaoBQAAAAAECigEBAAAAAasBAQAAAAECAAAAOwAgGwAAuQMAIAoLAACqAwAgDAAAqwMAIA0AAKwDACCKAQEAAAABjQFAAAAAAasBAQAAAAGvAQEAAAABsAEBAAAAAbIBAAAAsgECswEgAAAAAQIAAAABACAbAAC7AwAgBYoBAQAAAAGLAQEAAAABjQFAAAAAAZoBAQAAAAGbAQEAAAABA4oBAQAAAAGLAQEAAAABnQEAAACdAQIDigEBAAAAAYsBAQAAAAGNAUAAAAABAwAAAD4AIBsAALkDACAcAADCAwAgBAAAAD4AIBQAAMIDACCKAQEAhAIAIasBAQCEAgAhAooBAQCEAgAhqwEBAIQCACEDAAAAJQAgGwAAuwMAIBwAAMUDACAMAAAAJQAgCwAAggMAIAwAAIMDACANAACEAwAgFAAAxQMAIIoBAQCEAgAhjQFAAIUCACGrAQEAhAIAIa8BAQCEAgAhsAEBAIQCACGyAQAAgAOyASKzASAAtgIAIQoLAACCAwAgDAAAgwMAIA0AAIQDACCKAQEAhAIAIY0BQACFAgAhqwEBAIQCACGvAQEAhAIAIbABAQCEAgAhsgEAAIADsgEiswEgALYCACETAwAA5QIAIAYAAOYCACALAADnAgAgDQAA6QIAIA4AAOoCACCKAQEAAAABjQFAAAAAAZ4BAQAAAAGfAQEAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEgAAAAAaQBIAAAAAGlAQgAAAABpwEAAACnAQKoAQEAAAABqQEBAAAAAaoBQAAAAAECAAAABQAgGwAAxgMAIAoEAACpAwAgCwAAqgMAIA0AAKwDACCKAQEAAAABjQFAAAAAAasBAQAAAAGvAQEAAAABsAEBAAAAAbIBAAAAsgECswEgAAAAAQIAAAABACAbAADIAwAgAwAAAAMAIBsAAMYDACAcAADMAwAgFQAAAAMAIAMAALkCACAGAAC6AgAgCwAAuwIAIA0AAL0CACAOAAC-AgAgFAAAzAMAIIoBAQCEAgAhjQFAAIUCACGeAQEAhAIAIZ8BAQCEAgAhoAEBAIQCACGhAQEAhAIAIaIBAQCUAgAhowEgALYCACGkASAAtgIAIaUBCAC3AgAhpwEAALgCpwEiqAEBAIQCACGpAQEAhAIAIaoBQACFAgAhEwMAALkCACAGAAC6AgAgCwAAuwIAIA0AAL0CACAOAAC-AgAgigEBAIQCACGNAUAAhQIAIZ4BAQCEAgAhnwEBAIQCACGgAQEAhAIAIaEBAQCEAgAhogEBAJQCACGjASAAtgIAIaQBIAC2AgAhpQEIALcCACGnAQAAuAKnASKoAQEAhAIAIakBAQCEAgAhqgFAAIUCACEDAAAAJQAgGwAAyAMAIBwAAM8DACAMAAAAJQAgBAAAgQMAIAsAAIIDACANAACEAwAgFAAAzwMAIIoBAQCEAgAhjQFAAIUCACGrAQEAhAIAIa8BAQCEAgAhsAEBAIQCACGyAQAAgAOyASKzASAAtgIAIQoEAACBAwAgCwAAggMAIA0AAIQDACCKAQEAhAIAIY0BQACFAgAhqwEBAIQCACGvAQEAhAIAIbABAQCEAgAhsgEAAIADsgEiswEgALYCACEJBwAApQIAIAgAAKYCACAJAACoAgAgigEBAAAAAYsBAQAAAAGMAQEAAAABjQFAAAAAAZoBAQAAAAGbAQEAAAABAgAAAAsAIBsAANADACATAwAA5QIAIAYAAOYCACAMAADoAgAgDQAA6QIAIA4AAOoCACCKAQEAAAABjQFAAAAAAZ4BAQAAAAGfAQEAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEgAAAAAaQBIAAAAAGlAQgAAAABpwEAAACnAQKoAQEAAAABqQEBAAAAAaoBQAAAAAECAAAABQAgGwAA0gMAIAoEAACpAwAgDAAAqwMAIA0AAKwDACCKAQEAAAABjQFAAAAAAasBAQAAAAGvAQEAAAABsAEBAAAAAbIBAAAAsgECswEgAAAAAQIAAAABACAbAADUAwAgBYoBAQAAAAGLAQEAAAABjAEBAAAAAY0BQAAAAAGaAQEAAAABAwAAAAkAIBsAANADACAcAADZAwAgCwAAAAkAIAcAAJUCACAIAACWAgAgCQAAlwIAIBQAANkDACCKAQEAhAIAIYsBAQCEAgAhjAEBAIQCACGNAUAAhQIAIZoBAQCEAgAhmwEBAJQCACEJBwAAlQIAIAgAAJYCACAJAACXAgAgigEBAIQCACGLAQEAhAIAIYwBAQCEAgAhjQFAAIUCACGaAQEAhAIAIZsBAQCUAgAhAwAAAAMAIBsAANIDACAcAADcAwAgFQAAAAMAIAMAALkCACAGAAC6AgAgDAAAvAIAIA0AAL0CACAOAAC-AgAgFAAA3AMAIIoBAQCEAgAhjQFAAIUCACGeAQEAhAIAIZ8BAQCEAgAhoAEBAIQCACGhAQEAhAIAIaIBAQCUAgAhowEgALYCACGkASAAtgIAIaUBCAC3AgAhpwEAALgCpwEiqAEBAIQCACGpAQEAhAIAIaoBQACFAgAhEwMAALkCACAGAAC6AgAgDAAAvAIAIA0AAL0CACAOAAC-AgAgigEBAIQCACGNAUAAhQIAIZ4BAQCEAgAhnwEBAIQCACGgAQEAhAIAIaEBAQCEAgAhogEBAJQCACGjASAAtgIAIaQBIAC2AgAhpQEIALcCACGnAQAAuAKnASKoAQEAhAIAIakBAQCEAgAhqgFAAIUCACEDAAAAJQAgGwAA1AMAIBwAAN8DACAMAAAAJQAgBAAAgQMAIAwAAIMDACANAACEAwAgFAAA3wMAIIoBAQCEAgAhjQFAAIUCACGrAQEAhAIAIa8BAQCEAgAhsAEBAIQCACGyAQAAgAOyASKzASAAtgIAIQoEAACBAwAgDAAAgwMAIA0AAIQDACCKAQEAhAIAIY0BQACFAgAhqwEBAIQCACGvAQEAhAIAIbABAQCEAgAhsgEAAIADsgEiswEgALYCACETAwAA5QIAIAYAAOYCACALAADnAgAgDAAA6AIAIA0AAOkCACCKAQEAAAABjQFAAAAAAZ4BAQAAAAGfAQEAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEgAAAAAaQBIAAAAAGlAQgAAAABpwEAAACnAQKoAQEAAAABqQEBAAAAAaoBQAAAAAECAAAABQAgGwAA4AMAIAMAAAADACAbAADgAwAgHAAA5AMAIBUAAAADACADAAC5AgAgBgAAugIAIAsAALsCACAMAAC8AgAgDQAAvQIAIBQAAOQDACCKAQEAhAIAIY0BQACFAgAhngEBAIQCACGfAQEAhAIAIaABAQCEAgAhoQEBAIQCACGiAQEAlAIAIaMBIAC2AgAhpAEgALYCACGlAQgAtwIAIacBAAC4AqcBIqgBAQCEAgAhqQEBAIQCACGqAUAAhQIAIRMDAAC5AgAgBgAAugIAIAsAALsCACAMAAC8AgAgDQAAvQIAIIoBAQCEAgAhjQFAAIUCACGeAQEAhAIAIZ8BAQCEAgAhoAEBAIQCACGhAQEAhAIAIaIBAQCUAgAhowEgALYCACGkASAAtgIAIaUBCAC3AgAhpwEAALgCpwEiqAEBAIQCACGpAQEAhAIAIaoBQACFAgAhEwMAAOUCACAGAADmAgAgCwAA5wIAIAwAAOgCACAOAADqAgAgigEBAAAAAY0BQAAAAAGeAQEAAAABnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBIAAAAAGkASAAAAABpQEIAAAAAacBAAAApwECqAEBAAAAAakBAQAAAAGqAUAAAAABAgAAAAUAIBsAAOUDACAKBAAAqQMAIAsAAKoDACAMAACrAwAgigEBAAAAAY0BQAAAAAGrAQEAAAABrwEBAAAAAbABAQAAAAGyAQAAALIBArMBIAAAAAECAAAAAQAgGwAA5wMAIAMAAAADACAbAADlAwAgHAAA6wMAIBUAAAADACADAAC5AgAgBgAAugIAIAsAALsCACAMAAC8AgAgDgAAvgIAIBQAAOsDACCKAQEAhAIAIY0BQACFAgAhngEBAIQCACGfAQEAhAIAIaABAQCEAgAhoQEBAIQCACGiAQEAlAIAIaMBIAC2AgAhpAEgALYCACGlAQgAtwIAIacBAAC4AqcBIqgBAQCEAgAhqQEBAIQCACGqAUAAhQIAIRMDAAC5AgAgBgAAugIAIAsAALsCACAMAAC8AgAgDgAAvgIAIIoBAQCEAgAhjQFAAIUCACGeAQEAhAIAIZ8BAQCEAgAhoAEBAIQCACGhAQEAhAIAIaIBAQCUAgAhowEgALYCACGkASAAtgIAIaUBCAC3AgAhpwEAALgCpwEiqAEBAIQCACGpAQEAhAIAIaoBQACFAgAhAwAAACUAIBsAAOcDACAcAADuAwAgDAAAACUAIAQAAIEDACALAACCAwAgDAAAgwMAIBQAAO4DACCKAQEAhAIAIY0BQACFAgAhqwEBAIQCACGvAQEAhAIAIbABAQCEAgAhsgEAAIADsgEiswEgALYCACEKBAAAgQMAIAsAAIIDACAMAACDAwAgigEBAIQCACGNAUAAhQIAIasBAQCEAgAhrwEBAIQCACGwAQEAhAIAIbIBAACAA7IBIrMBIAC2AgAhBQQGAgUACwsdBQweBw0fCAcDAAEFAAoGAAMLDAUMEwcNFwgOGQkCBAcCBQAEAQQIAAUFAAYHAAEIAAIJDQUKDgUBCg8AAgcAAQgAAgIHAAEIAAIBCAACAwsaAAwbAA0cAAQEIAALIQAMIgANIwAAAAADBQAQIQARIgASAAAAAwUAECEAESIAEgAAAwUAFyEAGCIAGQAAAAMFABchABgiABkCAwABBgADAgMAAQYAAwUFAB4hACEiACJDAB9EACAAAAAAAAUFAB4hACEiACJDAB9EACACBwABCAACAgcAAQgAAgMFACchACgiACkAAAADBQAnIQAoIgApAwcAAQgAAgmKAQUDBwABCAACCZABBQMFAC4hAC8iADAAAAADBQAuIQAvIgAwAQgAAgEIAAIDBQA1IQA2IgA3AAAAAwUANSEANiIANwIHAAEIAAICBwABCAACAwUAPCEAPSIAPgAAAAMFADwhAD0iAD4PAgEQJAERJwESKAETKQEVKwEWLQwXLg0YMAEZMgwaMw4dNAEeNQEfNgwjOQ8kOhMlPAMmPQMnQAMoQQMpQgMqRAMrRgwsRxQtSQMuSwwvTBUwTQMxTgMyTwwzUhY0Uxo1VAI2VQI3VgI4VwI5WAI6WgI7XAw8XRs9XwI-YQw_YhxAYwJBZAJCZQxFaB1GaSNHagdIawdJbAdKbQdLbgdMcAdNcgxOcyRPdQdQdwxReCVSeQdTegdUewxVfiZWfypXgAEFWIEBBVmCAQVagwEFW4QBBVyGAQVdiAEMXokBK1-MAQVgjgEMYY8BLGKRAQVjkgEFZJMBDGWWAS1mlwExZ5kBCWiaAQlpnAEJap0BCWueAQlsoAEJbaIBDG6jATJvpQEJcKcBDHGoATNyqQEJc6oBCXSrAQx1rgE0dq8BOHewAQh4sQEIebIBCHqzAQh7tAEIfLYBCH24AQx-uQE5f7sBCIABvQEMgQG-ATqCAb8BCIMBwAEIhAHBAQyFAcQBO4YBxQE_"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/modules/auth/auth.service.ts
import jwt from "jsonwebtoken";
var secret = "ssdfsfsdfsdfsfsfsdfgswrwer";
var createUserAuth = async (payload) => {
  const { password, email, name } = payload;
  const existingUser = await prisma.user.findUnique({
    where: { email }
  });
  if (existingUser) {
    throw new Error("User already exists");
  }
  const hashedPass = await bcrypt.hash(password, 8);
  const user = await prisma.user.create({
    data: {
      name,
      email,
      password: hashedPass
    }
  });
  const token = jwt.sign(
    {
      id: user.id,
      name: user.name,
      email: user.email,
      role: user.role
    },
    secret,
    { expiresIn: "7d" }
  );
  return {
    token,
    user
  };
};
var loginUserAuth = async (payload) => {
  const user = await prisma.user.findUnique({
    where: {
      email: payload.email
    }
  });
  if (!user) {
    throw new Error("User not found");
  }
  const verifypass = await bcrypt.compare(payload.password, user.password);
  if (!verifypass) {
    throw new Error("Invalid credential");
  }
  const userData = {
    id: user.id,
    name: user.name,
    email: user.email,
    role: user.role
  };
  const token = jwt.sign(userData, secret, { expiresIn: "7d" });
  return {
    token,
    user
  };
};
var AuthService = {
  // Add service methods here
  createUserAuth,
  loginUserAuth
};

// src/modules/auth/auth.controller.ts
var registerUser = async (req, res) => {
  try {
    const result = await AuthService.createUserAuth(req.body);
    res.status(201).json({
      success: true,
      message: "User registered successfully",
      token: result.token,
      data: result.user
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "User registration failed",
      error: error.message
    });
  }
};
var loginUser = async (req, res) => {
  try {
    const result = await AuthService.loginUserAuth(req.body);
    const { password, ...userWithoutPassword } = result.user;
    res.cookie("token", result.token, {
      httpOnly: true,
      sameSite: "none",
      // 🔥 change this
      secure: true,
      maxAge: 7 * 24 * 60 * 60 * 1e3
    });
    res.status(200).json({
      success: true,
      message: "Login successful",
      token: result.token,
      data: userWithoutPassword
    });
  } catch (error) {
    res.status(401).json({
      success: false,
      message: error.message
    });
  }
};
var getMe = async (req, res) => {
  try {
    const user = req.user;
    res.status(200).json({
      success: true,
      data: user
    });
  } catch (error) {
    res.status(401).json({
      success: false,
      message: "Unauthorized"
    });
  }
};
var AuthController = {
  registerUser,
  loginUser,
  getMe
};

// src/middlewares/authMiddleware.ts
import jwt2 from "jsonwebtoken";
var authMiddleware = async (req, res, next) => {
  try {
    console.log("Cookies:", req.cookies);
    const token = await req.cookies?.token;
    console.log("token:", token);
    if (!token) {
      throw new Error("Unauthorized");
    }
    const decoded = jwt2.verify(token, process.env.JWT_SECRET);
    req.user = decoded;
    console.log("user:", req.user);
    next();
  } catch (error) {
    res.status(401).json({
      success: false,
      message: "Unauthorized"
    });
  }
};

// src/modules/auth/auth.router.ts
var router = express.Router();
router.post("/register", AuthController.registerUser);
router.post("/login", AuthController.loginUser);
router.get("/me", authMiddleware, AuthController.getMe);
var authRoutes = router;

// src/modules/user/user.router.ts
import express2 from "express";

// src/modules/user/user.service.ts
import bcrypt2 from "bcryptjs";
var getAllUsers = async () => {
  const users = await prisma.user.findMany({
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      isActive: true,
      createdAt: true
    }
  });
  return users;
};
var getUserById = async (id) => {
  const user = await prisma.user.findUnique({
    where: { id },
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      isActive: true,
      createdAt: true
    }
  });
  if (!user) {
    throw new Error("User not found");
  }
  return user;
};
var updateUser = async (id, payload) => {
  if (payload.password) {
    payload.password = await bcrypt2.hash(payload.password, 10);
  }
  const user = await prisma.user.update({
    where: { id },
    data: payload
  });
  return user;
};
var deleteUser = async (id) => {
  const user = await prisma.user.delete({
    where: { id }
  });
  return user;
};
var userService = {
  getAllUsers,
  getUserById,
  updateUser,
  deleteUser
};

// src/modules/user/user.controller.ts
var getAllUsers2 = async (req, res) => {
  try {
    const result = await userService.getAllUsers();
    res.status(200).json({
      success: true,
      message: "Users retrieved successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Failed to get users",
      error: error.message
    });
  }
};
var getUserById2 = async (req, res) => {
  try {
    const result = await userService.getUserById(req.params.id);
    res.status(200).json({
      success: true,
      message: "User retrieved successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message
    });
  }
};
var updateUser2 = async (req, res) => {
  try {
    const result = await userService.updateUser(
      req.params.id,
      req.body
    );
    res.status(200).json({
      success: true,
      message: "User updated successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "User update failed",
      error: error.message
    });
  }
};
var deleteUser2 = async (req, res) => {
  try {
    const result = await userService.deleteUser(req.params.id);
    res.status(200).json({
      success: true,
      message: "User deleted successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "User deletion failed",
      error: error.message
    });
  }
};
var updateUserStatus = async (req, res) => {
  try {
    const { id } = req.params;
    const { isActive } = req.body;
    if (!id) {
      return res.status(400).json({
        success: false,
        message: "Invalid user ID"
      });
    }
    const parsedIsActive = typeof isActive === "boolean" ? isActive : isActive === "true";
    console.log("parsedIsActive:", parsedIsActive);
    const user = await prisma.user.update({
      where: { id },
      data: { isActive: parsedIsActive }
    });
    console.log("user status", user);
    return res.json({
      success: true,
      data: user
    });
  } catch (error) {
    console.error("Update user status error:", error);
    return res.status(400).json({
      success: false,
      message: error.message
    });
  }
};

// src/modules/user/user.router.ts
var router2 = express2.Router();
router2.get("/:id", getUserById2);
router2.get("/", getAllUsers2);
router2.patch("/:id", updateUser2);
router2.delete("/:id", deleteUser2);
router2.patch("/:id/status", updateUserStatus);
var userRoutes = router2;

// src/modules/idea/idea.router.ts
import express3 from "express";

// src/modules/idea/idea.service.ts
var createIdea = async (payload, userId) => {
  console.log("userId:", userId);
  const idea = await prisma.idea.create({
    data: {
      ...payload,
      authorId: userId
    }
  });
  return idea;
};
var getAllIdeas = async (query) => {
  const { search, categoryId, status } = query;
  const ideas = await prisma.idea.findMany({
    where: {
      AND: [
        search ? {
          OR: [
            { title: { contains: search, mode: "insensitive" } },
            { description: { contains: search, mode: "insensitive" } },
            // 🌿 NEW: search by category name
            {
              category: {
                name: {
                  contains: search,
                  mode: "insensitive"
                }
              }
            }
          ]
        } : {},
        // 🌿 Filter by selected category
        categoryId ? { categoryId } : {},
        status ? { status } : {}
      ]
    },
    include: {
      author: {
        select: { id: true, name: true }
      },
      category: true,
      votes: true
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return ideas;
};
var getIdeaById = async (id, userId) => {
  const idea = await prisma.idea.findUnique({
    where: { id },
    include: {
      author: true,
      category: true,
      comments: {
        include: {
          replies: true
        }
      },
      votes: true,
      purchases: true
    }
  });
  if (!idea) {
    throw new Error("Idea not found");
  }
  if (idea.isPaid) {
    const purchased = idea.purchases.find(
      (p) => p.userId === userId
    );
    if (!purchased) {
      return {
        id: idea.id,
        title: idea.title,
        price: idea.price,
        message: "This is a paid idea. Please purchase to view details."
      };
    }
  }
  return idea;
};
var getIdeasByUserId = async (userId) => {
  const ideas = await prisma.idea.findMany({
    where: {
      authorId: userId
    },
    include: {
      author: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      category: true,
      votes: true
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return ideas;
};
var updateIdea = async (id, userId, payload) => {
  const idea = await prisma.idea.findUnique({
    where: { id }
  });
  if (!idea) throw new Error("Idea not found");
  if (idea.authorId !== userId) {
    throw new Error("Unauthorized");
  }
  if (idea.status === "APPROVED") {
    throw new Error("Approved ideas cannot be edited");
  }
  const updated = await prisma.idea.update({
    where: { id },
    data: payload
  });
  return updated;
};
var deleteIdea = async (id, userId) => {
  const idea = await prisma.idea.findUnique({
    where: { id }
  });
  if (!idea) throw new Error("Idea not found");
  if (idea.authorId !== userId) {
    throw new Error("Unauthorized");
  }
  const deleted = await prisma.idea.delete({
    where: { id }
  });
  return deleted;
};
var updateIdeaStatus = async (id, status) => {
  const idea = await prisma.idea.update({
    where: { id },
    data: { status }
  });
  return idea;
};
var ideaService = {
  createIdea,
  getAllIdeas,
  getIdeaById,
  getIdeasByUserId,
  updateIdea,
  deleteIdea,
  updateIdeaStatus
};

// src/modules/idea/idea.controller.ts
var createIdea2 = async (req, res) => {
  try {
    console.log("User ID:", req.user?.id);
    const result = await ideaService.createIdea(req.body, req.user?.id);
    res.status(201).json({
      success: true,
      message: "Idea created successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Idea creation failed",
      error: error.message
    });
  }
};
var getAllIdeas2 = async (req, res) => {
  try {
    console.log("req come");
    const result = await ideaService.getAllIdeas(req.query);
    res.status(200).json({
      success: true,
      message: "Ideas retrieved successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Failed to fetch ideas",
      error: error.message
    });
  }
};
var getIdeaById2 = async (req, res) => {
  try {
    const { id } = req.params;
    const userId = req.user?.id;
    const result = await ideaService.getIdeaById(id, userId);
    res.status(200).json({
      success: true,
      message: "Idea retrieved successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message
    });
  }
};
var getIdeasByUserId2 = async (req, res) => {
  try {
    const { userId } = req.params;
    if (!userId) {
      return res.status(400).json({
        success: false,
        message: "User ID is required"
      });
    }
    const ideas = await ideaService.getIdeasByUserId(userId);
    return res.status(200).json({
      success: true,
      data: ideas
    });
  } catch (error) {
    console.error("Get ideas by user error:", error);
    return res.status(400).json({
      success: false,
      message: "Failed to fetch ideas"
    });
  }
};
var updateIdea2 = async (req, res) => {
  try {
    const { id } = req.params;
    const userId = req.user?.id;
    const result = await ideaService.updateIdea(
      id,
      userId,
      req.body
    );
    res.status(200).json({
      success: true,
      message: "Idea updated successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Idea update failed",
      error: error.message
    });
  }
};
var deleteIdea2 = async (req, res) => {
  try {
    const { id } = req.params;
    const userId = req.user?.id;
    const result = await ideaService.deleteIdea(id, userId);
    res.status(200).json({
      success: true,
      message: "Idea deleted successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Idea deletion failed",
      error: error.message
    });
  }
};
var updateIdeaStatus2 = async (req, res) => {
  try {
    const { id } = req.params;
    const { status } = req.body;
    const result = await ideaService.updateIdeaStatus(id, status);
    res.status(200).json({
      success: true,
      message: "Idea status updated successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Failed to update status",
      error: error.message
    });
  }
};
var ideaController = {
  createIdea: createIdea2,
  getAllIdeas: getAllIdeas2,
  getIdeaById: getIdeaById2,
  getIdeasByUserId: getIdeasByUserId2,
  updateIdea: updateIdea2,
  deleteIdea: deleteIdea2,
  updateIdeaStatus: updateIdeaStatus2
};

// src/modules/idea/idea.router.ts
var router3 = express3.Router();
router3.get("/", ideaController.getAllIdeas);
router3.post("/", authMiddleware, ideaController.createIdea);
router3.get("/:id", authMiddleware, ideaController.getIdeaById);
router3.get("/user/:userId", authMiddleware, ideaController.getIdeasByUserId);
router3.patch("/:id", authMiddleware, ideaController.updateIdea);
router3.delete("/:id", authMiddleware, ideaController.deleteIdea);
router3.patch("/:id/status", authMiddleware, ideaController.updateIdeaStatus);
var ideaRoutes = router3;

// src/modules/category/category.router.ts
import express4 from "express";

// src/modules/category/category.service.ts
var createCategory = async (payload) => {
  const category = await prisma.category.create({
    data: payload
  });
  return category;
};
var getAllCategories = async () => {
  const categories = await prisma.category.findMany({
    include: {
      _count: {
        select: { ideas: true }
        // count ideas per category
      }
    },
    orderBy: {
      name: "asc"
    }
  });
  return categories;
};
var getCategoryById = async (id) => {
  const category = await prisma.category.findUnique({
    where: { id },
    include: {
      ideas: true
    }
  });
  if (!category) {
    throw new Error("Category not found");
  }
  return category;
};
var updateCategory = async (id, payload) => {
  const category = await prisma.category.update({
    where: { id },
    data: payload
  });
  return category;
};
var deleteCategory = async (id) => {
  const category = await prisma.category.delete({
    where: { id }
  });
  return category;
};
var categoryService = {
  createCategory,
  getAllCategories,
  getCategoryById,
  updateCategory,
  deleteCategory
};

// src/modules/category/category.controller.ts
var createCategory2 = async (req, res) => {
  try {
    const result = await categoryService.createCategory(req.body);
    res.status(201).json({
      success: true,
      message: "Category created successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Category creation failed",
      error: error.message
    });
  }
};
var getAllCategories2 = async (req, res) => {
  try {
    const result = await categoryService.getAllCategories();
    res.status(200).json({
      success: true,
      message: "Categories retrieved successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Failed to fetch categories",
      error: error.message
    });
  }
};
var getCategoryById2 = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await categoryService.getCategoryById(id);
    res.status(200).json({
      success: true,
      message: "Category retrieved successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message
    });
  }
};
var updateCategory2 = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await categoryService.updateCategory(
      id,
      req.body
    );
    res.status(200).json({
      success: true,
      message: "Category updated successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Category update failed",
      error: error.message
    });
  }
};
var deleteCategory2 = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await categoryService.deleteCategory(id);
    res.status(200).json({
      success: true,
      message: "Category deleted successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Category deletion failed",
      error: error.message
    });
  }
};
var categoryController = {
  createCategory: createCategory2,
  getAllCategories: getAllCategories2,
  getCategoryById: getCategoryById2,
  updateCategory: updateCategory2,
  deleteCategory: deleteCategory2
};

// src/middlewares/adminMiddleware.ts
import jwt3 from "jsonwebtoken";
var adminMiddleware = async (req, res, next) => {
  console.log("Cookies:", req.cookies);
  const token = await req.cookies?.token;
  const decoded = jwt3.verify(token, process.env.JWT_SECRET);
  req.user = decoded;
  console.log("user:", req.user);
  if (req.user?.role !== "ADMIN") {
    return res.status(403).json({
      success: false,
      message: "Forbidden: Admin only"
    });
  }
  next();
};

// src/modules/category/category.router.ts
var router4 = express4.Router();
router4.post("/", adminMiddleware, categoryController.createCategory);
router4.get("/", categoryController.getAllCategories);
router4.get("/:id", authMiddleware, categoryController.getCategoryById);
router4.patch("/:id", adminMiddleware, categoryController.updateCategory);
router4.delete("/:id", adminMiddleware, categoryController.deleteCategory);
var categoryRoutes = router4;

// src/modules/vote/vote.router.ts
import express5 from "express";

// src/modules/vote/vote.service.ts
var voteIdea = async (userId, ideaId, type) => {
  const existing = await prisma.vote.findUnique({
    where: {
      userId_ideaId: {
        userId,
        ideaId
      }
    }
  });
  if (existing && existing.type === type) {
    await prisma.vote.delete({
      where: {
        userId_ideaId: { userId, ideaId }
      }
    });
    return { message: "Vote removed" };
  }
  if (existing) {
    return prisma.vote.update({
      where: {
        userId_ideaId: { userId, ideaId }
      },
      data: { type }
    });
  }
  return prisma.vote.create({
    data: {
      userId,
      ideaId,
      type
    }
  });
};
var removeVote = async (userId, ideaId) => {
  return prisma.vote.delete({
    where: {
      userId_ideaId: {
        userId,
        ideaId
      }
    }
  });
};
var getVoteSummary = async (ideaId) => {
  const votes = await prisma.vote.findMany({
    where: { ideaId }
  });
  const upVotes = votes.filter((v) => v.type === "UP").length;
  const downVotes = votes.filter((v) => v.type === "DOWN").length;
  return {
    upVotes,
    downVotes,
    score: upVotes - downVotes
  };
};
var voteService = {
  voteIdea,
  removeVote,
  getVoteSummary
};

// src/modules/vote/vote.controller.ts
var voteIdea2 = async (req, res) => {
  try {
    const userId = req.user?.id;
    const { ideaId, type } = req.body;
    if (!userId) {
      return res.status(401).json({
        success: false,
        message: "Unauthorized"
      });
    }
    const result = await voteService.voteIdea(userId, ideaId, type);
    res.status(200).json({
      success: true,
      message: "Vote processed",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Voting failed",
      error: error.message
    });
  }
};
var removeVote2 = async (req, res) => {
  try {
    const userId = req.user?.id;
    console.log(userId);
    const { ideaId } = req.params;
    console.log(req.params);
    if (!userId) {
      return res.status(401).json({
        success: false,
        message: "Unauthorized"
      });
    }
    const result = await voteService.removeVote(userId, ideaId);
    res.status(200).json({
      success: true,
      message: "Vote removed",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Failed to remove vote",
      error: error.message
    });
  }
};
var getVoteSummary2 = async (req, res) => {
  try {
    const { ideaId } = req.params;
    const result = await voteService.getVoteSummary(ideaId);
    res.status(200).json({
      success: true,
      message: "Vote summary fetched",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Failed to fetch votes",
      error: error.message
    });
  }
};
var voteController = {
  voteIdea: voteIdea2,
  removeVote: removeVote2,
  getVoteSummary: getVoteSummary2
};

// src/modules/vote/vote.router.ts
var router5 = express5.Router();
router5.post("/", authMiddleware, voteController.voteIdea);
router5.delete("/:ideaId", authMiddleware, voteController.removeVote);
router5.get("/:ideaId", voteController.getVoteSummary);
var voteRoutes = router5;

// src/modules/feedback/feedback.router.ts
import express6 from "express";

// src/modules/feedback/feedback.service.ts
var createOrUpdateFeedback = async (ideaId, message) => {
  const existing = await prisma.feedback.findUnique({
    where: { ideaId }
  });
  if (existing) {
    return prisma.feedback.update({
      where: { ideaId },
      data: { message }
    });
  }
  return prisma.feedback.create({
    data: {
      ideaId,
      message
    }
  });
};
var getFeedbackByIdeaId = async (ideaId) => {
  const feedback = await prisma.feedback.findUnique({
    where: { ideaId }
  });
  if (!feedback) {
    throw new Error("Feedback not found");
  }
  return feedback;
};
var deleteFeedback = async (ideaId) => {
  return prisma.feedback.delete({
    where: { ideaId }
  });
};
var feedbackService = {
  createOrUpdateFeedback,
  getFeedbackByIdeaId,
  deleteFeedback
};

// src/modules/feedback/feedback.controller.ts
var createFeedback = async (req, res) => {
  try {
    const { ideaId, message } = req.body;
    const result = await feedbackService.createOrUpdateFeedback(
      ideaId,
      message
    );
    res.status(200).json({
      success: true,
      message: "Feedback saved successfully",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Failed to save feedback",
      error: error.message
    });
  }
};
var getFeedback = async (req, res) => {
  try {
    const { ideaId } = req.params;
    const result = await feedbackService.getFeedbackByIdeaId(ideaId);
    res.status(200).json({
      success: true,
      message: "Feedback retrieved",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message
    });
  }
};
var deleteFeedback2 = async (req, res) => {
  try {
    const { ideaId } = req.params;
    await feedbackService.deleteFeedback(ideaId);
    res.status(200).json({
      success: true,
      message: "Feedback deleted successfully"
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Failed to delete feedback",
      error: error.message
    });
  }
};
var feedbackController = {
  createFeedback,
  getFeedback,
  deleteFeedback: deleteFeedback2
};

// src/modules/feedback/feedback.router.ts
var router6 = express6.Router();
router6.post("/", authMiddleware, adminMiddleware, feedbackController.createFeedback);
router6.get("/:ideaId", feedbackController.getFeedback);
router6.delete("/:ideaId", authMiddleware, adminMiddleware, feedbackController.deleteFeedback);
var feedbackRoutes = router6;

// src/app.ts
import cookieParser from "cookie-parser";

// src/modules/payment/payment.controller.ts
import Stripe from "stripe";
var stripe = new Stripe(process.env.STRIPE_SECRET_KEY, {
  apiVersion: "2026-03-25.dahlia"
});
var createPaymentIntent = async (req, res) => {
  try {
    const userId = req.user?.id;
    const { ideaId, amount } = req.body;
    console.log(ideaId, userId, amount);
    if (!userId || !ideaId) {
      return res.status(400).json({
        message: "Missing userId or ideaId"
      });
    }
    const paymentIntent = await stripe.paymentIntents.create({
      amount,
      currency: "usd",
      metadata: {
        userId,
        ideaId
      }
    });
    res.json({
      clientSecret: paymentIntent.client_secret
    });
  } catch (error) {
    res.status(400).json({ error: "Payment failed" });
  }
};

// src/modules/payment/payment.router.ts
import express7 from "express";
var router7 = express7.Router();
router7.post("/create-payment-intent", authMiddleware, createPaymentIntent);
var paymentRoutes = router7;

// src/utils/stripe.ts
import Stripe2 from "stripe";
var stripe2 = new Stripe2(process.env.STRIPE_SECRET_KEY, {
  apiVersion: "2026-03-25.dahlia"
});

// src/modules/payment/stripe.webhook.ts
import express8 from "express";
var stripeWebhook = express8.raw({ type: "application/json" });
var handleWebhook = async (req, res) => {
  const sig = req.headers["stripe-signature"];
  if (!sig || Array.isArray(sig)) {
    return res.status(400).send("Invalid Stripe signature");
  }
  let event;
  try {
    event = stripe2.webhooks.constructEvent(
      req.body,
      sig,
      process.env.STRIPE_WEBHOOK_SECRET
    );
  } catch (err) {
    console.log("Webhook error:", err.message);
    return res.status(400).send(`Webhook Error`);
  }
  if (event.type === "payment_intent.succeeded") {
    const paymentIntent = event.data.object;
    console.log(paymentIntent);
    const ideaId = paymentIntent.metadata.ideaId;
    const userId = paymentIntent.metadata.userId;
    console.log("\u2705 Payment success:", ideaId, userId);
    if (!userId || !ideaId) {
      throw new Error("Missing userId or ideaId");
    }
    await prisma.purchase.create({
      data: {
        userId,
        ideaId
      }
    });
  }
  res.json({ received: true });
};

// src/modules/purchase/purchase.router.ts
import express9 from "express";

// src/modules/purchase/purchase.service.ts
var createPurchase = async (userId, ideaId) => {
  console.log(userId, ideaId);
  const existing = await prisma.purchase.findUnique({
    where: {
      userId_ideaId: {
        userId,
        ideaId
      }
    }
  });
  if (existing) {
    throw new Error("Already purchased");
  }
  const purchase = await prisma.purchase.create({
    data: {
      userId,
      ideaId
    }
  });
  return purchase;
};
var getUserPurchases = async (userId) => {
  return prisma.purchase.findMany({
    where: { userId },
    include: {
      idea: true
    }
  });
};
var hasPurchased = async (userId, ideaId) => {
  const purchase = await prisma.purchase.findUnique({
    where: {
      userId_ideaId: {
        userId,
        ideaId
      }
    }
  });
  return !!purchase;
};
var purchaseService = {
  createPurchase,
  getUserPurchases,
  hasPurchased
};

// src/modules/purchase/purchase.controller.ts
var createPurchase2 = async (req, res) => {
  try {
    const userId = req.user?.id;
    const { ideaId } = req.body;
    if (!userId) {
      return res.status(401).json({
        success: false,
        message: "Unauthorized"
      });
    }
    const result = await purchaseService.createPurchase(userId, ideaId);
    res.status(201).json({
      success: true,
      message: "Purchase successful \u{1F33F}",
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};
var getMyPurchases = async (req, res) => {
  try {
    const userId = req.user?.id;
    if (!userId) {
      return res.status(401).json({
        success: false,
        message: "Unauthorized"
      });
    }
    const result = await purchaseService.getUserPurchases(userId);
    res.json({
      success: true,
      data: result
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};
var checkPurchase = async (req, res) => {
  try {
    const userId = req.user?.id;
    const { ideaId } = req.params;
    if (!userId) {
      return res.status(401).json({
        success: false,
        message: "Unauthorized"
      });
    }
    const purchased = await purchaseService.hasPurchased(userId, ideaId);
    res.json({
      success: true,
      purchased
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: error.message
    });
  }
};

// src/modules/purchase/purchase.router.ts
var router8 = express9.Router();
router8.post("/", authMiddleware, createPurchase2);
router8.get("/my", authMiddleware, getMyPurchases);
router8.get("/check/:ideaId", authMiddleware, checkPurchase);
var purchaseRoutes = router8;

// src/app.ts
var app = express10();
app.use(cookieParser());
app.post(
  "/api/webhook",
  stripeWebhook,
  handleWebhook
);
app.use(express10.json());
app.use(
  cors({
    // origin: "http://localhost:4000",
    origin: "https://green-community-frontend.vercel.app",
    credentials: true
  })
);
app.use((req, res, next) => {
  console.log("Raw Cookie Header:", req.headers.cookie);
  next();
});
app.post("/webhook", (req, res) => {
  console.log("Received webhook:", req.body);
  res.status(200).send("Webhook received");
});
app.get("/", (req, res) => {
  res.send("Server is running");
});
app.use("/api/auth", authRoutes);
app.use("/api/users", authMiddleware, userRoutes);
app.use("/api/idea", ideaRoutes);
app.use("/api/categories", categoryRoutes);
app.use("/api/votes", voteRoutes);
app.use("/api/feedback", feedbackRoutes);
app.use("/api/payment", paymentRoutes);
app.use("/api/purchase", purchaseRoutes);
var app_default = app;

// src/server.ts
var PORT = process.env.PORT || 3e3;
async function server() {
  try {
    await prisma.$connect();
    app_default.listen(PORT, () => {
      console.log(`server running on port ${PORT}`);
    });
  } catch (error) {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  }
}
server();
